package com.minipay.adminbff;
import java.net.URI;import java.time.Duration;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpHeaders;import org.springframework.http.ResponseEntity;import org.springframework.security.core.Authentication;import org.springframework.security.oauth2.client.OAuth2AuthorizeRequest;import org.springframework.security.oauth2.client.ReactiveOAuth2AuthorizedClientManager;import org.springframework.web.bind.annotation.RequestMapping;import org.springframework.web.bind.annotation.RestController;import org.springframework.web.reactive.function.client.WebClient;import org.springframework.web.server.ServerWebExchange;import reactor.core.publisher.Mono;
@RestController public class AdminProxyController {
 private final ReactiveOAuth2AuthorizedClientManager clients;private final WebClient web;private final String identity,payment,wallet,commerce;
 public AdminProxyController(ReactiveOAuth2AuthorizedClientManager clients,WebClient.Builder web,@Value("${minipay.identity-internal-url}")String identity,@Value("${minipay.payment-internal-url}")String payment,@Value("${minipay.wallet-internal-url}")String wallet,@Value("${minipay.commerce-internal-url}")String commerce){this.clients=clients;this.web=web.build();this.identity=identity;this.payment=payment;this.wallet=wallet;this.commerce=commerce;}
 @RequestMapping("/api/v1/admin/**") public Mono<ResponseEntity<byte[]>> proxy(Authentication auth,ServerWebExchange exchange){var req=OAuth2AuthorizeRequest.withClientRegistrationId("minipay-admin").principal(auth).attribute(ServerWebExchange.class.getName(),exchange).build();return clients.authorize(req).switchIfEmpty(Mono.error(new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.UNAUTHORIZED))).flatMap(c->forward(c.getAccessToken().getTokenValue(),exchange)).timeout(Duration.ofSeconds(6));}
 private Mono<ResponseEntity<byte[]>> forward(String token,ServerWebExchange e){String path=e.getRequest().getPath().value();String tail=path.substring("/api/v1/admin".length());String base=(tail.startsWith("/accounts")||tail.startsWith("/action-audits")||tail.startsWith("/login-audits")||tail.startsWith("/summary")||tail.startsWith("/me/"))?identity:tail.startsWith("/orders/food-orders")?commerce:(tail.startsWith("/wallets")||tail.startsWith("/ledger-transactions")||tail.startsWith("/orders/collection-records"))?wallet:payment;String query=e.getRequest().getURI().getRawQuery();var request=web.method(e.getRequest().getMethod()).uri(URI.create(base+path+(query==null?"":"?"+query))).headers(h->{h.setBearerAuth(token);copy(e,h,"X-Request-Id");copy(e,h,"Idempotency-Key");copy(e,h,"X-Reason");copy(e,h,HttpHeaders.CONTENT_TYPE);copy(e,h,HttpHeaders.IF_MATCH);copy(e,h,HttpHeaders.USER_AGENT);if(e.getRequest().getRemoteAddress()!=null)h.set("X-Admin-Client-IP",e.getRequest().getRemoteAddress().getAddress().getHostAddress());});return request.body(e.getRequest().getBody(),org.springframework.core.io.buffer.DataBuffer.class).exchangeToMono(r->r.bodyToMono(byte[].class).defaultIfEmpty(new byte[0]).map(body->ResponseEntity.status(r.statusCode()).headers(headers->{r.headers().contentType().ifPresent(headers::setContentType);}).body(body)));}
 private static void copy(ServerWebExchange e,HttpHeaders h,String n){String v=e.getRequest().getHeaders().getFirst(n);if(v!=null)h.set(n,v);}
}
