CREATE TABLE IF NOT EXISTS "yshop_material" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "creator" varchar(100) DEFAULT NULL,
    "type" char(2) NOT NULL,
    "group_id" varchar(32) DEFAULT NULL,
    "name" varchar(200) NOT NULL,
    "url" varchar(500) DEFAULT '',
    "updater" varchar(64) DEFAULT NULL,
    "update_time" datetime DEFAULT NULL,
    "deleted" bit(1) NOT NULL DEFAULT '0',
    "tenant_id" bigint DEFAULT '0',
    PRIMARY KEY ("id")
);
